// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package song

import (
	"context"
)

type Querier interface {
	DeleteSong(ctx context.Context, id int32) error
	InsertSong(ctx context.Context, arg *InsertSongParams) (int32, error)
	SelectSongText(ctx context.Context, id int32) (string, error)
	UpdateSong(ctx context.Context, arg *UpdateSongParams) error
}

var _ Querier = (*Queries)(nil)
